// Generated by tools/analysis/bed.py -- do not edit.
//
// The night bed, and the insects in it.
//
// The bed is the third-octave curve of the quietest third of the frames of
// every reference in the library, median across 44 files -- wind, distant
// water, recorder hiss and a chorus too far away to be individual callers. It
// is collapsed to the eight octave bands the engine runs and the bank's gains
// are solved against it in power, non-negatively, on a log-frequency grid.
//
// The solve is done here rather than at run time, which is the one place this
// differs from ShoreBreak, SkyHowl, RiverFlow and CrackleBlaze: their controls
// reshape the target, so they have to solve it live. Nothing here does, so what
// ships is the answer. Residual after the solve: 3.4 dB RMS across the grid.
//
// The insect band is measured the same way -- from the quiet frames, because a
// cricket band is *steady* and that is what separates it from the top end of a
// croak. 3 references carry one that is both steady and clear of the octave
// around it.
//
// **This is the weakest measurement in the plugin, and it is worth knowing
// why.** The library has no recording of insects on their own: what is measured
// here is the cricket bed *behind* a scops owl and behind a chorus of frogs,
// isolated by being narrow, high and steady where everything else in those
// files is none of the three. Two recordings carry a prominent trill rate and
// they disagree by an octave, 33 and 49 Hz, which may well be a katydid and a
// cricket rather than an error. Three or four clean recordings of a summer
// night would replace all of this with something worth the name.
//
// Regenerating needs the reference recordings in !dev/references, which are not
// part of this repository:
//
//     cd tools/analysis && python3 bed.py --emit
//
#pragma once

namespace nightlife {

constexpr int kNumBedBands = 8;

// Octave centres, Hz.
constexpr float kBedBandHz[kNumBedBands] = {63.0f, 125.0f, 250.0f, 500.0f, 1000.0f, 2000.0f, 4000.0f, 8000.0f};

// The measured bed's own level in each band, dB below the loudest -- what the
// bank is solved against, kept for the tools that check the solve.
constexpr float kBedBandDb[kNumBedBands] = {-15.5f, -15.0f, -4.4f, 0.0f, -0.8f, -5.8f, -18.0f, -21.5f};

// The solved gains, as amplitudes with the loudest at 1.0. These are what the
// engine multiplies its bandpasses by.
constexpr float kBedBandGain[kNumBedBands] = {0.9223f, 0.0946f, 0.6731f, 1.0000f, 0.5341f, 0.1720f, 0.0527f, 0.3191f};

// The insect band: a narrow, steady, pulsed band of noise, which is what a
// chorus of crickets and katydids is. Not a caller and not a croak -- there is
// no pitch contour and no body resonance in it at all.
constexpr float kInsectHz = 2982.4f;      // measured carrier
constexpr float kInsectQ = 20.69f;       // carrier over its own -6 dB width
constexpr float kInsectTrillHz = 49.2f; // the pulse rate on the band
constexpr float kInsectShare = 0.029f;   // its share of the quiet-frame energy

// The two filters on the ends of the bank. A bank of octave-wide bandpasses
// cannot make a steep end -- an Svf bandpass's skirts fall at 6 dB per octave,
// and the measured night falls 20 dB between 2.5 and 5 kHz -- so these make the
// ends and the bank is solved for what is left.
constexpr float kBedLpHz = 2200.0f;
constexpr float kBedHpHz = 40.0f;

} // namespace nightlife
