// Generated by tools/analysis/frogs.py -- do not edit.
//
// What a croak is, measured. A croak is not a pitch contour: it is a pulse
// train through a body resonance, and these are the numbers that separate one
// frog from another.
//
//   pulseHz     the rate of the train. This is the species, and the first
//               thing a field guide lists.
//   pulses      how many of them one croak holds.
//   pulseDepth  how far the envelope falls between pulses. Measured at 0.96 to
//               0.99 across the library -- a croak is a train of separate
//               pulses and not a tremolo on a tone.
//   f1, f2      the two resonances. f2 sits at a measured median 0.50 of f1
//               across the library, which is why the second one is not
//               optional: a single resonance is a beep.
//   q1          how sharp the first one is. Measured 9 to 31, median 20 -- and
//               it is measured with a *linear* smoother 2.5 pulse rates wide,
//               because a third-octave smoother returns a third of an octave
//               for every recording and calls it a Q of 4.2.
//   riseSec,    the croak's own envelope.
//   fallSec
//   ratePerMin  how often that frog called in the recording it came from.
//
// Regenerating needs the reference recordings in !dev/references, which are not
// part of this repository:
//
//     cd tools/analysis && python3 frogs.py --emit
//
#pragma once

namespace nightlife {

struct CroakType {
   float durationSec;
   float pulseHz;
   float pulses;
   float pulseDepth;
   float f1Hz;
   float f2Hz;
   float q1;
   float riseSec;
   float fallSec;
   float ratePerMin;
};

constexpr CroakType kCroaks[] = {
   {0.3251f,    9.8f,   4.0f, 0.978f,  2168.8f,  1012.4f,  23.9f, 0.0730f, 0.0336f,  119.0f},  // frogs-croak1.wav
   {0.2148f,   12.3f,   2.0f, 0.991f,  2310.4f,  1202.8f,  30.6f, 0.0773f, 0.0499f,  148.2f},  // multiple-frog-croaking-sounds.wav
   {0.1920f,   13.4f,   2.0f, 0.978f,  1529.3f,  1831.4f,  26.5f, 0.0589f, 0.0814f,  109.9f},  // croaking-frogs.wav
   {0.6080f,   20.1f,  13.0f, 0.960f,  1534.8f,   441.5f,  23.3f, 0.2839f, 0.1779f,   48.0f},  // frogs-6.wav
   {0.0427f,   33.5f,   8.0f, 0.971f,  3298.8f,  1716.8f,  16.8f, 0.0139f, 0.0242f,  480.4f},  // leopard-frogs-croaking.wav
   {0.3733f,   48.5f,  18.0f, 0.984f,  2016.4f,   955.4f,  10.0f, 0.1319f, 0.0925f,  119.4f},  // frogs-croaking.wav
   {0.3251f,   56.3f,  16.0f, 0.972f,  1978.4f,   948.8f,  11.5f, 0.0367f, 0.0694f,  146.6f},  // frog-sound.wav
   {0.3715f,   68.9f,  25.0f, 0.970f,  2108.9f,  1069.6f,   9.1f, 0.2178f, 0.0870f,  123.4f},  // frogs-croaking-in-pond.wav
};

constexpr int kNumCroaks = 8;

// The library-wide medians the table above is relative to.
constexpr float kLibraryCroakSec = 0.3251f;
constexpr float kLibraryPulseHz = 26.8f;
constexpr float kLibraryCroakHz = 2062.6f;
constexpr float kLibraryCroakRate = 121.4f;

// The Fano factor of the croak arrivals, measured over the whole library at
// four window lengths. A Poisson process is exactly 1.0 at every one of them.
//
//     window     50 ms   250 ms     1 s     4 s
//     median      0.90     0.81    0.59    0.30
//
// Every window is below 1, and it falls as the window grows. **A frog chorus is
// more regular than a Poisson process, not less** -- which is the opposite of
// what CrackleBlaze measured for fire, where the Fano factor is 3.90 at one
// second. So the chorus scheduler here is not Poisson: each frog calls on a
// period of its own with a bounded jitter around it, and the chorus is the sum
// of those. Spawning it as a Poisson process gives a texture that is audibly
// more clumped than any of the recordings.
constexpr float kFanoWindows[] = {0.05f, 0.25f, 1.0f, 4.0f};
constexpr float kFanoMeasured[] = {0.90f, 0.81f, 0.59f, 0.30f};

} // namespace nightlife
