#pragma once

// The measured species table. Generated by tools/analysis/species.py -- do not
// edit by hand; edit the script and re-run it.
//
// Each row is one species of flying insect, reduced from the reference library
// to the six numbers the engine needs. `rateHz` and `hnrDb` are measurements:
// the median wingbeat rate across that species' recordings, and the median
// share of band energy that lies on a harmonic of it. The four shaper
// coefficients are a fit -- one one-pole shelf and one SVF bandpass, fitted
// against those filters' own discrete-time responses to the species' median
// harmonic stack, with the overall level divided out.
//
// The stack itself is carried alongside as `stack`, in dB relative to the
// fundamental, so the fit can be checked against what it was fitted to without
// going back to the recordings. It is what the manual's tables print.
//
// A table of numbers is not a sample; see the suite's note on pure synthesis.
// Nothing here reproduces recorded audio -- these say what shape to give a
// signal the plugin generates itself.

#include <cstdint>

namespace insectswarm {

constexpr int kStackHarmonics = 10;

struct SpeciesRow {
   const char *name;
   float rateHz;      // measured median wingbeat rate
   float tiltDb;      // shelf tilt about 300 Hz, fitted
   float formantHz;   // the bandpass centre, fitted
   float formantRes;  // its resonance, 0..1, in Svf::setCutoff's units
   float formantMix;  // how much of the chain is the bandpass, 0..1, fitted
   float stroke;      // the upstroke against the downstroke, 0..1, fitted
   float hnrDb;       // measured harmonic-to-noise ratio of the buzz
   float voiced;      // measured share of frames that are a wingbeat at all
   float fitErrDb;    // RMS residual of the shaper fit against the stack
   int   refs;        // recordings the row was taken from
   float stack[kStackHarmonics]; // the measured stack, dB re the fundamental
};

constexpr SpeciesRow kSpecies[] = {
   {"Hornet", 85.7f, 6.00f, 151.5f, 0.9400f, 0.9750f, 0.000f, 1.96f, 0.939f, 3.29f, 1,
    {0.0f, 10.7f, 0.1f, -5.0f, -15.6f, -22.7f, -23.4f, -26.1f, -26.4f, -27.4f}},
   {"Bumblebee", 143.4f, -15.00f, 322.7f, 0.8617f, 0.6750f, 0.100f, 6.34f, 0.741f, 1.55f, 3,
    {0.0f, 11.7f, 7.3f, 5.7f, 2.7f, 3.5f, -2.8f, -6.9f, -9.9f, -7.9f}},
   {"Wasp", 150.6f, 3.50f, 215.6f, 0.9400f, 0.9500f, 0.100f, 6.56f, 0.930f, 3.76f, 2,
    {0.0f, 4.1f, -15.3f, -17.0f, -14.3f, -19.3f, -19.0f, -25.0f, -25.9f, -26.1f}},
   {"Housefly", 193.1f, 4.50f, 375.3f, 0.9400f, 0.5750f, 0.000f, 5.90f, 0.860f, 1.50f, 6,
    {0.0f, 4.6f, -5.5f, -6.3f, -6.2f, -9.6f, -13.2f, -16.9f, -17.7f, -19.7f}},
   {"Honeybee", 221.2f, 36.00f, 2189.9f, 0.9400f, 0.7500f, 0.000f, 6.63f, 0.564f, 2.12f, 16,
    {0.0f, -1.7f, -12.3f, -13.7f, -14.0f, -16.3f, -18.4f, -21.4f, -21.9f, -25.1f}},
   {"Mosquito", 463.7f, 9.00f, 1137.4f, 0.9400f, 0.6750f, 0.000f, 16.04f, 0.921f, 1.60f, 5,
    {0.0f, -0.3f, -1.9f, -9.6f, -5.0f, -9.2f, -12.6f, -17.4f, -19.0f, -23.2f}},
   {"Dragonfly", 118.8f, 16.00f, 1196.2f, 0.9008f, 0.8250f, 0.000f, 1.07f, 0.076f, 3.95f, 2,
    {0.0f, -7.5f, -0.1f, -13.7f, -13.3f, -14.1f, -12.9f, -7.0f, -17.5f, -16.1f}},
};

constexpr int kNumSpecies = static_cast<int>(sizeof(kSpecies) / sizeof(kSpecies[0]));

// The two stridulating mechanisms. A tymbal and a file-and-scraper are both a
// train of clicks ringing a resonant body, so they share a model and differ
// only in its numbers -- and they differ in it sharply. A cricket's resonator
// is twice as sharp as a cicada's (Q 26 against 13) and its clicks arrive
// seven times more slowly (36/s against 268), which is the whole distance
// between a pure whistling trill and a dry rattle.
struct StridulatorRow {
   const char *name;
   float carrierHz;
   float q;
   float pulseHz;
   float echemeHz;
   float duty;
   int   refs;
};

constexpr StridulatorRow kStridulators[] = {
   {"Cicada", 5548.8f, 13.2f, 268.4f, 12.54f, 0.478f, 14},
   {"Cricket", 4517.6f, 25.8f, 35.9f, 10.51f, 0.325f, 9},
};

constexpr int kNumStridulators =
   static_cast<int>(sizeof(kStridulators) / sizeof(kStridulators[0]));

} // namespace insectswarm
