# Turns presets/*.thunderclap into a C++ header of raw string literals, so the
# plugin can serve its factory presets even when installed as a single file.
#
# Invoked as: cmake -DPRESET_DIR=... -DOUTPUT=... -P embed_presets.cmake

file(GLOB preset_files "${PRESET_DIR}/*.thunderclap")
list(SORT preset_files)

set(body "// Generated by cmake/embed_presets.cmake -- do not edit.\n")
string(APPEND body "#pragma once\n\nnamespace thunderclap {\n\n")
string(APPEND body "struct BuiltinPreset {\n   const char *loadKey;\n   const char *text;\n};\n\n")
string(APPEND body "static const BuiltinPreset kBuiltinPresets[] = {\n")

foreach(preset_file ${preset_files})
   get_filename_component(preset_key "${preset_file}" NAME_WE)
   file(READ "${preset_file}" preset_text)
   string(APPEND body "   {\"${preset_key}\",\n    R\"THUNDERCLAP(${preset_text})THUNDERCLAP\"},\n")
endforeach()

string(APPEND body "};\n\n")
string(APPEND body "static const unsigned kNumBuiltinPresets =\n")
string(APPEND body "   sizeof(kBuiltinPresets) / sizeof(kBuiltinPresets[0]);\n\n")
string(APPEND body "} // namespace thunderclap\n")

file(WRITE "${OUTPUT}" "${body}")
