"""Generates src/dsp/vent_samples.h from the reference recordings.

    python3 tools/make-vent-samples.py

This is the one place in the whole suite where audio is embedded rather than
synthesised, and it is deliberate: the synthesised version of this particular
sound was not convincing, and the recordings are licensed in a way that allows
them to be shipped. Everything else in SkyHowl is still computed at run time.

Source: 54 recordings by Jagadamba, freesound.org sound ids 253799-253826,
licensed Creative Commons Attribution 4.0. The attribution that licence
requires is in skyhowl/LICENSE. The recordings themselves stay in !dev/ and are
not committed; what is committed is the generated header, which is why this
script records exactly what it did to them.

The output is 48 kHz 16-bit mono, base64'd into a string literal:

  - 48 kHz because the plugin runs at 48 kHz most of the time, and at that rate
    playback is a straight read with no resampling at all. Storing at 24 kHz
    halves the size but measured 12-18 dB SNR in the worst case once the
    playback interpolator had put it back up to 48 -- linear interpolation is a
    poor reconstruction filter near Nyquist, and that cost is not worth 1.2 MB.
  - base64 rather than a byte array because a hex array of the same data is
    six times the source size.
  - loudness matched, because the originals' RMS spans 14.4 dB and a random
    pick should not jump in level between clicks. Each is scaled to a target
    RMS, then pulled back if that would push its peak over the ceiling.
"""
import base64
import math
import os
import struct
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
# The suite's WAV reader, which walks the chunks properly. ffmpeg writes a LIST
# chunk before the data, so the payload is not at a fixed offset and assuming
# it is silently yields a few hundred frames instead of a few hundred thousand.
sys.path.insert(0, os.path.join(HERE, "..", "..", "shared", "tools", "analysis"))
import wavio
PLUGIN = os.path.dirname(HERE)
SRC = os.path.join(PLUGIN, "!dev", "references", "farts")
OUT = os.path.join(PLUGIN, "src", "dsp", "vent_samples.h")

RATE = 48000
TARGET_RMS_DBFS = -16.0
PEAK_CEILING_DBFS = -1.0
LINE = 100  # base64 characters per source line


def decode(path, work):
    """mp3 -> 48 kHz mono int16 via ffmpeg, which is a development tool only."""
    wav = os.path.join(work, "d.wav")
    subprocess.run(["ffmpeg", "-v", "error", "-y", "-i", path, "-ac", "1",
                    "-ar", str(RATE), "-c:a", "pcm_s16le", wav], check=True)
    x, sr = wavio.read_wav(wav)
    if sr != RATE:
        raise RuntimeError("ffmpeg gave %d Hz, expected %d" % (sr, RATE))
    return [int(round(v * 32767.0)) for v in wavio.to_mono(x)]


def main():
    if not os.path.isdir(SRC):
        print("no reference directory: %s" % SRC, file=sys.stderr)
        return 1
    names = sorted(f for f in os.listdir(SRC) if f.lower().endswith(".mp3"))
    if not names:
        print("no .mp3 files in %s" % SRC, file=sys.stderr)
        return 1

    target = 10.0 ** (TARGET_RMS_DBFS / 20.0) * 32767.0
    ceiling = 10.0 ** (PEAK_CEILING_DBFS / 20.0) * 32767.0

    blob = bytearray()
    index = []
    levels = []
    with tempfile.TemporaryDirectory() as work:
        for name in names:
            s = decode(os.path.join(SRC, name), work)
            if not s:
                continue
            rms = (sum(float(v) * v for v in s) / len(s)) ** 0.5
            peak = max(abs(v) for v in s)
            if rms <= 0 or peak <= 0:
                continue
            gain = min(target / rms, ceiling / peak)
            index.append((len(blob) // 2, len(s)))
            for v in s:
                q = int(round(v * gain))
                blob += struct.pack("<h", -32768 if q < -32768 else (32767 if q > 32767 else q))
            levels.append(20.0 * math.log10(max(1e-9, rms * gain / 32767.0)))

    b64 = base64.b64encode(bytes(blob)).decode("ascii")
    frames = len(blob) // 2

    with open(OUT, "w") as f:
        f.write("// Generated by tools/make-vent-samples.py -- do not edit.\n")
        f.write("//\n")
        f.write("// %d recordings by Jagadamba, freesound.org ids 253799-253826, licensed\n"
                % len(index))
        f.write("// Creative Commons Attribution 4.0. See skyhowl/LICENSE for the credit that\n")
        f.write("// licence requires. Decoded to %d Hz 16-bit mono, loudness matched to\n" % RATE)
        f.write("// %.0f dBFS RMS under a %.0f dBFS peak ceiling, and base64'd.\n"
                % (TARGET_RMS_DBFS, PEAK_CEILING_DBFS))
        f.write("#pragma once\n\n#include <cstdint>\n\nnamespace skyhowl {\n\n")
        f.write("struct VentSampleSpan {\n   uint32_t offset;\n   uint32_t frames;\n};\n\n")
        f.write("inline constexpr uint32_t kVentSampleRate = %d;\n" % RATE)
        f.write("inline constexpr uint32_t kVentSampleFrames = %d;\n\n" % frames)
        f.write("inline constexpr VentSampleSpan kVentSpans[] = {\n")
        for off, n in index:
            f.write("   {%d, %d},\n" % (off, n))
        f.write("};\n\n")
        f.write("inline constexpr unsigned kNumVentSamples =\n")
        f.write("   sizeof(kVentSpans) / sizeof(kVentSpans[0]);\n\n")
        f.write("// base64 of %d little-endian int16 frames.\n" % frames)
        f.write("inline constexpr char kVentSampleBase64[] =\n")
        for i in range(0, len(b64), LINE):
            f.write('   "%s"\n' % b64[i:i + LINE])
        f.write("   ;\n\n} // namespace skyhowl\n")

    print("%d samples, %d frames, %.1f s" % (len(index), frames, frames / float(RATE)))
    print("loudness matched to %.1f .. %.1f dBFS RMS (was a 14.4 dB spread)"
          % (min(levels), max(levels)))
    print("blob %.0f KB -> base64 %.0f KB -> header %.0f KB"
          % (len(blob) / 1024.0, len(b64) / 1024.0, os.path.getsize(OUT) / 1024.0))
    return 0


if __name__ == "__main__":
    sys.exit(main())
